# Funding information for Pull Request Report
# This is optional but helps with project sustainability

# GitHub Sponsors (username)
# github: [dbtreasure]

# Other funding platforms
# ko_fi: username
# patreon: username
# open_collective: username

# Custom funding URL
# custom: ["https://example.com/sponsor"]